apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: opentlc-mgr
    eventing.knative.dev/lastModifier: opentlc-mgr
  name: order-trigger
  finalizers:
    - kafka.triggers.eventing.knative.dev
    - kafka.namespaced.triggers.eventing.knative.dev
  labels:
    eventing.knative.dev/broker: kafka-broker-sample
    app.kubernetes.io/part-of: broker-demo
spec:
  broker: broker-demo
  filter:
    attributes:
      kafkaheadersubject: order
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-service-display
      namespace: eventing-demo